### ISSUE TITLE
LinkRefiner

### ISSUE THREAD

**Issue by deepseek** [hanish3464/webtoon_text_detection_with_CRAFT#2]
@hanish3464 
Did you consider integrating the [LinkRefiner](https://github.com/clovaai/CRAFT-pytorch#test-instruction-using-pretrained-model) from the CRAFT paper?
It is helpful for detecting long text-lines.

![LinkRefiner](https://user-images.githubusercontent.com/49877135/68575570-616a4900-047d-11ea-8517-e31995171681.jpg)

**Comment by hanish3464** [comment]
Thanks @deepseek 

But There is no needs for link refiner in my project. 

Because I want to detect just characters on images. In my code, line detection(postprocess using opencv) already exists for sorting order of characters!

Thanks for interests about my project
